### ISSUE TITLE
Is there any subroutine to read variables of a Group

### ISSUE THREAD

**Issue by sxcgc** [alex-robinson/ncio#10]
This project is a very useful tools. But when I read a variable of a Group, I write like "nc_ndims(filename,"/G1/Longitude")", program will raise a error "ncio:: error: NetCDF: Variable not found".So what should I do to read variables of Group?
thanks

**Comment by alex-robinson** [comment]
Unfortunately we didn’t get as far as including specific treatment for group variables. I cannot say to what extent the code can handle such cases.
